config/routes.rb
Hogar::Application.routes.draw do
  match "/leads" => 'leads#send_thank_lead', :as => :leads, :via => :post
  match "/*id" => 'high_voltage/pages#show', :as => :page, :format => false
  root :to => 'high_voltage/pages#show', :id => 'index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController

  def send_thank_lead
    email = params[:email]
    LeadMailer.thank_lead(email).deliver
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{:content => "DR_qm3gqrMWaoe-ujL-SQFimJkER3LdoSYeRbmLDarA", :name => "google-site-verification"}/
    %meta{charset: "utf-8"}
    %meta(http-equiv= "X-UA-Compatible" content= "IE=Edge,chrome=1")
    %meta{name: "viewport", content:"width=device-width, initial-scale=1.0"}
    %title= yield(:page_title)
    %meta{name: "keywords", content:yield(:keywords)}
    %meta{name: "description", content:yield(:description)} 
    %meta{name: "author", content: "ubiqua"} 

    / open graph meta tags -- esto es lo que sale en FB :
    %meta{property:"og:title", content: "ubiqua | Soluciones de Software Empresarial"}
    %meta{property:"og:type", content: "website"} 
    %meta{property:"og:image", content: "/assets/logo-dark.png"}
    %meta{property:"og:url", content:"http://www.ubiqua.me"}
    %meta{property:"og:description", content:"ubiqua es una compañia que desarrolla software empresarial en panama. Ofrecemos una applicacion que administra la fuerza de ventas de empresas."}
   
    

    = csrf_meta_tags

    / le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      %script{type: "text/javascript", src:"//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"}

    / le stylesheets
    = stylesheet_link_tag "application", media: "all"

  %body
    %header
      / le navbar
      .navbar.navbar-fixed-top
        .navbar-inner
          .container
            %a.btn.btn-navbar.button-nav{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
              %span.icon-bar.bars
              %span.icon-bar.bars
              %span.icon-bar.bars
            / logo
            %a.brand.logo{href: "index"}  
              %img{src: "/assets/logo.png"}
            / menu
            .navigation.nav-collapse.collapse
              %ul.nav.topnav
                = yield :navbar_btns
    %section#subintro
      = yield :subintro    

    /
      le breadcrumbs
      %section#breadcrumb
        .container
          .row
            .span12
              %ul.breadcrumb.notop
                %li.active Inicio

    /le content
    %section#maincontent            
      = yield

    /le footer
    %footer.footer
      .container
        .row-fluid
          .span3
            .widget
              / logo
              %a.brand.logo{href: "index"}
                %img{src: "/assets/logo-dark.png"}
              %address
                %i.fa.fa-map-marker
                %strong UBIQUA, S.A.
                %br
                Paitilla Office Tower, oficina 7-02
                %br 
                Paitilla
                %br
                Ciuidad de Panamá, Panamá
              %span
                %i.fa.fa-phone
                %a{href: "tel:+5072096707"} +507 209 6707
              %br
              %span
                %i.fa.fa-envelope
                %a{href: "mailto:ghurtado@ubiqua.me"} ghurtado@ubiqua.me 
              %br
              .widget
                %ul.social-links
                  %li
                    %a{href: "https://www.facebook.com/ubiqua.me", title: "Facebook"}
                      %i.icon-rounded.icon-32.fa.fa-facebook.social-media.footer
                  %li
                    %a{href: "https://twitter.com/ubiquame", title: "Twitter", rel: "publisher"}
                      %i.icon-rounded.icon-32.fa.fa-twitter.social-media.footer
                  %li
                    %a{href: "http://www.linkedin.com/company/3087639", title: "LinkedIn", rel: "publisher"}
                      %i.icon-rounded.icon-32.fa.fa-linkedin.social-media.footer
                  %li
                    %a{href: "https://github.com/ubiqua", title: "Github"}
                      %i.icon-rounded.icon-32.fa.fa-github-alt.social-media.footer
          .span3
            .widget
              %h5 Producto
              %ul.regular
                %li
                  %a{href: "/catalog"} Catálogo
                %li
                  %a{href: "/orders"} Envío de pedidos
              /  
                %li
                  %a{href: "/manager"} Análisis de ventas
          .span3
            .widget
              %h5 Empresa
              %ul.regular
                %li
                  %a{href: "/about"} Sobre Nosotros
                %li
                  %a{href: "/contact"} Contáctanos
                %li
                  %a{href: "http://www.ubiquame.blogspot.com/"} Blog
                %li
                  %a{href: "/trisfera"} Recursos de Trisfera Conf

          .span3
            .widget
              %h5 Acertijos
              %ul.regular
                %li
                  %a{href: "/bolas"} bolas
                %li
                  %a{href: "/burro"} burro
                %li
                  %a{href: "/carrera"} carrera
                %li
                  %a{href: "/cuerdas"} cuerdas
                %li
                  %a{href: "/granjero"} granjero
                %li
                  %a{href: "/guardia"} guardias
                %li
                  %a{href: "/relojes"} relojes
      .verybottom
        .container
          .row
            .span12
              %p &copy; ubiqua 2014
    
    / le javascripts -- Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

    / le google analytics
    :javascript
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-40074427-1']);
      _gaq.push(['_setDomainName', 'ubiqua.me']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

app/views/pages/_navbar_btns.html.haml
%li{class: active_if_home}
  %a.mobile-nav{href: "/index"} Inicio
%li{class: active_if_product}
  %a.mobile-nav.dropdown-toggle{"data-toggle" => "dropdown", href:"#"} 
    Producto
    %i.icon-chevron-down
  %ul.dropdown-menu
    %li 
      %a{href:"/catalog"} Catálogo
    %li 
      %a{href:"/orders"} Envío de pedidos
  /
    %li 
      %a{href:"/manager"} Análisis de ventas
%li{class: active_if_blog}
  %a.mobile-nav{href: "http://www.ubiquame.blogspot.com/"} Blog
%li 
  %input.btn.btn-color.moving-cta{type:"submit", value:"Pruébalo por 14 días GRATIS", onclick:"location.href='/signup'"}

app/views/pages/about.html.haml
- content_for :page_title do
  ubiqua | Sobre Nosotros
-content_for :description do
  Con la colaboracion de cuatro amigos, ubiqua fue concevido como una alternativa a los precios elevados y la pobre calidad de software empresarial existente
-content_for :keywords do
  Programadores Panama, web programador, java , android, agiliza la fuerza de ventas, programa para celulares, programadores de soluciones tecnologicas, desarrollo de software panama


- content_for :navbar_btns do
  = render partial: "pages/navbar_btns", locals: { active_if_home: "", active_if_product: "", active_if_blog: "", active_if_contact: "" }
-content_for :subintro do
  %section#subintro.about-us
    .container
      %section.title-area
        %span.main-message.animated.bounceInDown
          %strong Conoce
          a nuestro equipo de trabajo
.container
  .row
  /
    .span12
      %h2 Sobre Nosotros
      %h3 ubiqua
      %p
        Lorem ipsum dolor sit amet, per cu graece fierent dignissim, et reque dicat blandit quo, ad mel stet aperiri insolens. Eum esse ancillae conclusionemque at. Ut nec ullum homero. Autem legimus in sed. Ad eam iudico delectus, aperiri maiestatis eos eu. Mea viris abhorreant at, eirmod vivendo an ius.
      %p
        Cu nec iudicabit percipitur, eu sit possim viderer malorum. In homero audiam aperiri eos, ea noster virtute usu, vim id inimicus philosophia. Id propriae percipit consulatu nam, in verear sensibus deseruisse has. Magna moderatius ei eum, at eum tractatos contentiones. Noster electram at his, partem repudiandae contentiones ea eam. Nemore forensibus delicatissimi eu his. Est salutandi imperdiet te, sale magna commune ex pri. Diam alia sanctus ei nam, ut vel pertinax delicata, facilis invenire sea ex. Pro eu sale prompta, congue inermis mea ei.
      %p
        Ei eam diam quando sapientem, ad pri enim vero eleifend. Eu everti inimicus his, te his nisl vocent. At rebum omnium blandit duo, malis scriptorem vis te. Altera mandamus eam ei, ex usu odio mutat debitis. At quo laudem iuvaret albucius, magna mundi honestatis pri ut, eos ei suas feugait. Vim tation dicant ornatus in.
  .row.team
    .span12
      %h3 El Equipo
      .row
        .span6
          %img.team-member-pic{height: "200px", src: "/assets/jorge.jpg", width: "200px"}
          .team-member-info
            %h4 Jorge L. García
            %p
              Ingeniero en Ciencias de Sistemas enfocado en sistemas económicos y financieros de University of Pennsylvania. Jorge además hizo una especialización en Matemáticas y Economía.
            .widget
              %ul.social-links
                %li
                  %a{href: "https://www.facebook.com/jgarciach", title: "Facebook"}
                    %i.icon-rounded.icon-32.fa.fa-facebook.social-media
                %li
                  %a{href: "https://twitter.com/jgarciachap", title: "Twitter"}
                    %i.fa.fa-twitter.icon-rounded.icon-32.social-media
                %li
                  %a{href: "http://www.linkedin.com/pub/jorge-luis-garcia-chapman/17/877/94", title: "LinkedIn"}
                    %i.fa.fa-linkedin.icon-rounded.icon-32.social-media
                %li
                  %a{href: "https://github.com/jgarciach", title: "Github"}
                    %i.icon-rounded.icon-32.fa.fa-github-alt.social-media
        .span6
          %img.team-member-pic{height: "200px", src: "/assets/gaby.png", width: "200px"}/
          .team-member-info
            %h4 Gabriela Hurtado
            %p
              Licenciada en Finanzas y Mercadeo de McIntire School of Commerce parte de University of Virginia. Gabriela también hizo una especialización en Relaciones Internacionales.
            .widget
              %ul.social-links
                %li
                  %a{href: "https://www.facebook.com/gabriela.hurtado7", title: "Facebook"}
                    %i.icon-rounded.icon-32.fa.fa-facebook.social-media
                %li
                  %a{href: "https://twitter.com/GabyHurtado7", title: "Twitter"}
                    %i.fa.fa-twitter.icon-rounded.icon-32.social-media
                %li
                  %a{href: "http://www.linkedin.com/pub/gabriela-hurtado/33/ba4/a28/en", title: "LinkedIn"}
                    %i.fa.fa-linkedin.icon-rounded.icon-32.social-media
                %li
                  %a{href: "https://github.com/gabrielah", title: "Github"}
                    %i.icon-rounded.icon-32.fa.fa-github-alt.social-media
      .row
        .span6
          %img.team-member-pic{height: "200px", src: "/assets/diego.png", width: "200px"}/
          .team-member-info
            %h4 Diego Molino
            %p
              Ingeniero Industrial enfocado en operaciones de Stanford University. Además, Diego hizo una especialización en Ciencias Computacionales.
            .widget
              %ul.social-links
                %li
                  %a{href: "https://www.facebook.com/diego.molino", title: "Facebook"}
                    %i.icon-rounded.icon-32.fa.fa-facebook.social-media
                %li
                  %a{href: "https://twitter.com/dmolino17", title: "Twitter"}
                    %i.fa.fa-twitter.icon-rounded.icon-32.social-media
                %li
                  %a{href: "http://www.linkedin.com/pub/diego-molino/32/b46/b42", title: "LinkedIn"}
                    %i.fa.fa-linkedin.icon-rounded.icon-32.social-media
                %li
                  %a{href: "https://github.com/dmolino", title: "Github"}
                    %i.icon-rounded.icon-32.fa.fa-github-alt.social-media
        .span6
          %img.team-member-pic{height: "200px", src: "/assets/jose.jpeg", width: "200px"}/
          .team-member-info
            %h4 José R. Varela
            %p
              Licenciado en Negocios y Relaciones Internacionales de Huntsman Program del Wharton School en University of Pennsylvania. Además hizo una especialización en Ciencias Computacionales.
            .widget
              %ul.social-links
                %li
                  %a{href: "https://www.facebook.com/joservarelaf", title: "Facebook"}
                    %i.icon-rounded.icon-32.fa.fa-facebook.social-media
                %li
                  %a{href: "https://twitter.com/jose_r_varela", title: "Twitter"}
                    %i.fa.fa-twitter.icon-rounded.icon-32.social-media
                %li
                  %a{href: "http://www.linkedin.com/pub/jose-varela/13/458/9a3", title: "LinkedIn"}
                    %i.fa.fa-linkedin.icon-rounded.icon-32.social-media
                %li
                  %a{href: "https://github.com/cabe56", title: "Github"}
                    %i.icon-rounded.icon-32.fa.fa-github-alt.social-media
      .row
        .span6
          %img.team-member-pic{height: "200px", src: "/assets/alberto.jpg", width: "200px"}
          .team-member-info
            %h4.intern-name Alberto Picard-Ami
            %div.position
              Pasante 2013
            %p
              Estudiante de Ingeniería Industrial enfocado en operaciones de University of Toronto. Además, Alberto hizo una especialización en negocios.
            .widget
              %ul.social-links
                %li
                  %a{href: "https://www.facebook.com/alberto.picardami?ref=tn_tnmn", title: "Facebook"}
                    %i.icon-rounded.icon-32.fa.fa-facebook.social-media
                %li
                  %a{href: "https://twitter.com/apicardami", title: "Twitter"}
                    %i.fa.fa-twitter.icon-rounded.icon-32.social-media
                %li
                  %a{href: "http://ca.linkedin.com/in/albertopicardami/", title: "LinkedIn"}
                    %i.fa.fa-linkedin.icon-rounded.icon-32.social-media
        .span6
          %img.team-member-pic{height: "200px", src: "/assets/sabi.jpeg", width: "200px"}/
          .team-member-info
            %h4.intern-name Maria Isabel Vega
            %div.position
              Pasante 2013
            %p
              Estudiante de cuarto año de Ingeniería en Ciencias Computacionales en Stanford University, enfocada en el estudio de la interacción persona-computador.
            .widget
              %ul.social-links
                %li
                  %a{href: "https://www.facebook.com/mariaisabel.vega.m", title: "Facebook"}
                    %i.icon-rounded.icon-32.fa.fa-facebook.social-media
                %li
                  %a{href: "http://www.linkedin.com/profile/view?id=100202851&locale=en_US&trk=tyah", title: "LinkedIn"}
                    %i.fa.fa-linkedin.icon-rounded.icon-32.social-media
      .row
        .span6
          %img.team-member-pic{height: "200px", src: "/assets/marielos.png", width: "200px"}/
          .team-member-info
            %h4.intern-name Marielos Sanson
            %div.position
              Pasante 2013
            %p
              Estudiante de cuarto año de Ingeniería Industrial en Stanford University con enfoque en operaciones.
            .widget
              %ul.social-links
                %li
                  %a{href: "https://www.facebook.com/marielos.sanson", title: "Facebook"}
                    %i.icon-rounded.icon-32.fa.fa-facebook.social-media
        .span6
          %img.team-member-pic{height: "200px", src: "/assets/jaime.png", width: "200px"}/
          .team-member-info
            %h4.intern-name Jaime Sánchez
            %div.position
              Pasante 2013
            %p
              Estudiante de tercer año de Ciencias Computacionales en Tufts University.
            .widget
              %ul.social-links
                %li
                  %a{href: "https://www.facebook.com/jaime25", title: "Facebook"}
                    %i.icon-rounded.icon-32.fa.fa-facebook.social-media

app/views/pages/bolas.html.haml
- content_for :page_title do
  ubiqua | Acertijo: bolas
-content_for :description do
  ubiqua es una compañia que desarrolla software empresarial en panama. Ofrecemos una applicacion que administra la fuerza de ventas de empresas.
- content_for :navbar_btns do
  = render partial: "pages/navbar_btns", locals: { active_if_home: "", active_if_product: "", active_if_blog: "", active_if_contact: "" }
-content_for :subintro do
  %section#subintro.brainteaser.balls
    .container
      %section.title-area
        %span.main-message.animated.bounceInDown
          Acertijo
        %br
        %span.sub-message.animated.bounceInUp
          bolas en la balanza

.container
  .row
    .span12
      %p.lead
        %i.fa.fa-quote-left
        Hay nueve bolas del mismo tamaño, ocho pesan lo mismo y una pesa un poquito más. ¿Cómo sabes cual es la más pesada, si solo puedes pesarlas usando una balanza y solo puedes usar la balanza dos veces?
        %i.fa.fa-quote-right
      %a#show-ans.btn.btn-default.btn-small{href: "#"} ver respuesta
      .well.answer{style: "display: none;"}
        %strong Respuesta:
        %p
          Divides las nueve bolas en tres grupos de tres. Pesas dos de los grupos. Si son iguales, escoges el que no pesaste, si no, escoges el grupo más pesado. Luego, escoges dos bolas de ese grupo y las pesas. Si una es más pesada, esa es la bola que buscas. Si las dos pesan lo mismo, la bola que buscas es la que no pesaste de ese grupo.

app/views/pages/burro.html.haml
- content_for :page_title do
  ubiqua | Acertijo: burro
-content_for :description do
  ubiqua es una compañia que desarrolla software empresarial en panama. Ofrecemos una applicacion que administra la fuerza de ventas de empresas.
-content_for :keywords do
  innovación empresarial, administración de ventas, software contable, software empresarial, soluciones en software, Panama,  fuerza de ventas, mejora tu servicio al cliente, desarollo de software

- content_for :navbar_btns do
  = render partial: "pages/navbar_btns", locals: { active_if_home: "", active_if_product: "", active_if_blog: "", active_if_contact: "" }
-content_for :subintro do
  %section#subintro.brainteaser.donkey
    .container
      %section.title-area
        %span.main-message.animated.bounceInDown
          Acertijo
        %br
        %span.sub-message.animated.bounceInUp
          el viaje del burro 

.container
  .row
    .span12
      %p.lead
        %i.fa.fa-quote-left
        Un burro viaja exactamente la misma distancia diariamente. Dos de sus patas han viajado 40 km y las otras dos 41km. El burro es completamente normal (no hay 1 km entre sus patas). ¿Cómo es esto posible?
        %i.fa.fa-quote-right
      %a#show-ans.btn.btn-default.btn-small{href: "#"} ver respuesta
      .well.answer{style: "display: none;"}
        %strong Respuesta:
        %p
          El burro el trayecto que recorre el burro es un círculo por lo tanto las patas de en la parte de afuera del círculo caminan más distancia que las patas  en la parte de adentro del círculo.

app/views/pages/carrera.html.haml
- content_for :page_title do
  ubiqua | Acertijo: carrera
-content_for :description do
  ubiqua es una compañia que desarrolla software empresarial en panama. Ofrecemos una applicacion que administra la fuerza de ventas de empresas.
-content_for :keywords do
  Software de ventas, catalogo en la nube, herramienta de ventas, Panama, base de datos nube, sap, facturacion, cotizaciones, erp, sistemas a la medida, tiempo real, software contable,

- content_for :navbar_btns do
  = render partial: "pages/navbar_btns", locals: { active_if_home: "", active_if_product: "", active_if_blog: "", active_if_contact: "" }
-content_for :subintro do
  %section#subintro.brainteaser.camels
    .container
      %section.title-area
        %span.main-message.animated.bounceInDown
          Acertijo
        %br
        %span.sub-message.animated.bounceInUp
          carrera de camellos

.container
  .row
    .span12
      %p.lead
        %i.fa.fa-quote-left
        Un padre le dice a sus dos hijos que, para decidir quien va a heredar su fortuna, deben competir en una carrera en sus camellos. El camello que llegue de último a Estambul, gana. Los hijos, confundidos, le piden consejos a un hombre sabio. Después de escucharlo, los hijos se van en los camellos hacia Estambul lo más rápido que pueden. ¿Qué les dijo el hombre sabio?
        %i.fa.fa-quote-right
      %a#show-ans.btn.btn-default.btn-small{href: "#"} ver respuesta
      .well.answer{style: "display: none;"}
        %strong Respuesta:
        %p
          El hombre sabio le dice a los hermanos que intercambien camellos.

app/views/pages/contact.html.haml
- content_for :page_title do
  ubiqua | Contáctanos
-content_for :description do
  ubiqua es una compañia que desarrolla software empresarial en panama. Ofrecemos una applicacion que administra la fuerza de ventas de empresas.
-content_for :keywords do
  Panama, Innovadores en software, web applicatoins, Compañia que desarrolla software empresarial, bussiness intelligence,  software para iphone,software para android. 

- content_for :navbar_btns do
  = render partial: "pages/navbar_btns", locals: { active_if_home: "", active_if_product: "", active_if_blog: "", active_if_contact: "active" }
-content_for :subintro do
  %section#subintro.brainteaser.contact-map
    %iframe{src: "https://maps.google.com/maps/ms?msa=0&msid=216549314379670436232.0004d85e767f42522a541&ie=UTF8&t=m&ll=8.99182,-79.511662&spn=0.042388,0.128746&z=14&output=embed"}
    .container
      %section.title-area
        %br
        %span.sub-message.animated.bounceInUp
          Orgullosamente ubicados en 
          %strong Panamá 

.container
  .row
    .span12
      %aside
        .widget
          %h4 Contáctanos
          %ul
            %li
              %label
                %i.fa.fa-phone
                %strong Teléfono :
                %a{href: "tel:+50762135138"} +507 6213 5138
            %li
              %label
                %i.fa.fa-envelope
                %strong Correo Electrónico :
                %a{href: "mailto:ghurtado@ubiqua.me"} ghurtado@ubiqua.me
            %li
              %label
                %i.fa.fa-map-marker
                %strong Dirección :
                %address.address
                  %strong UBIQUA, S.A.
                  %br/
                  Calle 50, Plaza Sitio Antiguao Local 1 PB
                  %br/
                  Urbanización San Francisco
                  %br/
                  Ciudad de Panamá, Panamá
        .widget
          %ul.social-links
            %li
              %a{href: "https://www.facebook.com/ubiqua.me", title: "Facebook"}
                %i.icon-rounded.icon-32.fa.fa-facebook.social-media
            %li
              %a{href: "https://twitter.com/ubiquame", title: "Twitter", rel: "publisher"}
                %i.icon-rounded.icon-32.fa.fa-twitter.social-media
            %li
              %a{href: "http://www.linkedin.com/company/3087639", title: "LinkedIn", rel: "publisher"}
                %i.icon-rounded.icon-32.fa.fa-linkedin.social-media
            %li
              %a{href: "https://github.com/ubiqua", title: "Github"}
                %i.icon-rounded.icon-32.fa.fa-github-alt.social-media
  /
    .span8
      .spacer30
      %form.contact-form{action: "#", method: "post", name: "comment-form"}
        .row
          .span4
            %label
              Nombre
              %span *
            %input#form-name.input-block-level{placeholder: "Tu nombre", type: "text"}/
          .span4
            %label
              Correo Electrónico
              %span *
            %input#form-email.email-contact.input-block-level{placeholder: "Tu correo electrónico", type: "email"}/
          .span8
            %label
              Mensaje
              %span *
            %textarea.input-block-level{placeholder: "Tu mensaje", rows: "9"}
            %button.btn.btn-color.btn-movil{type: "submit"} Enviar

app/views/pages/product.html.haml
- content_for :page_title do
  ubiqua | Administrador de Ventas Empresariales
-content_for :description do
  ubiqua AVE  es una aplicación para dispositivos móviles que conecta y administra la fuerza de ventas de tu empresa.
-content_for :keywords do
  Software de ventas, catalogo en la nube, herramienta de ventas, Panama, base de datos nube, sap, facturacion, cotizaciones, erp, sistemas a la medida, tiempo real, software contable,

- content_for :navbar_btns do
  = render partial: "pages/navbar_btns", locals: { active_if_home: "", active_if_aboutus: "", active_if_blog: "", active_if_contact: "", active_if_product: "active" }
-content_for :subintro do
  %section#subintro.product-picture
    .container
      %section.call-to-action.span8
        %span.main-message.animated.bounceInDown
          %strong ubiqua 
          AVE
.container.product-content
  .product-description
    Ahora tus gerentes y vendedores tendrán una herramienta completa que los acompañará a través de todo el proceso de ventas. Con ella, el gerente podrá monitorear las ventas de sus vendedores en tiempo real. Mientras tanto, los vendedores podrán mostrar sus productos organizadamente, hacer pedidos para clientes y enviarlos directamente al sistema central de la empresa desde su dispositivo móvil.
  %hr
  .row-fluid 
    .span6.feature-info
      %h2 Análisis de ventas
      %div
      Mejora tu Business Intelligence entrando a reportes con información de ventas según vendedor, cliente y/o producto desde cualquier dispositivo móvil o computadora. Con este análisis, localiza fácilmente áreas con oportunidad de mejorar dentro de tu negocio en tiempo real.
    .span6
      %img.feature-pic{src:'/assets/mobileCar.jpg',alt:''}
  %hr
  .row-fluid 
    .span6.feature-info
      %h2 Catálogo Digital
      %div
      Informa a tus clientes de tus productos mostrándoles precios actualizados, fotos y detalles de manera organizada e interactiva. El catálogo puede ser accesado sólo por personal autorizado. Además se conecta y sincroniza con tu base de datos de productos y lista de clientes así que no tienes que preocuparte por actualizarlo tu mismo. Está almacenado en la nube haciéndolo veloz, escalable y disponible en tiempo real.
    .span6
      %img.feature-pic{src:'/assets/tabletShow.jpg',alt:''}
  %hr
  .row-fluid 
    .span6.feature-info
      %h2.feature-title Envío de órdenes de compra y cotizaciones
      %div
      Disminuye error humano en pedidos enviando pedidos  y cotizaciones para clientes digitalmente. Maximiza el tiempo de tus empleados enviando los pedidos directamente a tu sistema eliminando órdenes a papel, revisiones de pedidos y otros procesos manuales. El sistema de envío se conecta con el catálogo digital así que el vendedor escoge los artículos del catálogo que el cliente desea y envía un resumen del pedido al sistema central de la compañia.
    .span6
      %img.feature-pic{src:'/assets/paperWork.jpeg',alt:''}
  %hr 
  %h2.feature-title 
    Funcionamiento de la Aplicación 
  %ul
    %li Captación de pedidos en modo offline
    %li Accesibilidad desde cualquier dispositivo móvil o computadora en tiempo real
    %li Integración con base de datos de productos y lista de clientes
    %li Aplicación en la nube brindando escalabilidad, rapidez y confianza
  %img{src:'/assets/process.png',alt:''}
  %hr
  .rec.well
    %h3 Danos tu email si te interesa recibir más información sobre nuestros servicios:
    = form_tag(leads_path, class: "form-inline", remote: true) do
      = email_field_tag "email", nil, id: "form-email", class: "landingpage", placeholder: "Email"
      = submit_tag "Enviar", class: "btn btn-large btn-color landingpage send-btn"
  .thanks.well
    %h3 Gracias, pronto te estaremos contactando!